document.write( '<script>\n' );
document.write( '  function setSkin(a){\n' );
document.write( '    localStorage.setItem(\'playerSkin\', a);\n' );
document.write( '    alert(\"Skin changed!\")\n' );
document.write( '  }\n' );
document.write( '</script>\n' );
document.write( '<style>\n' );
document.write( '  img{\n' );
document.write( '    width:50px;\n' );
document.write( '    height:50px;\n' );
document.write( '    cursor:pointer;\n' );
document.write( '  }\n' );
document.write( '</style>\n' );
document.write( '<img src=\"https://mmccall0813.github.io/skinImg/1.png\" onclick=\"setSkin(1)\"></img>\n' );
document.write( '<img src=\"https://mmccall0813.github.io/skinImg/2.png\" onclick=\"setSkin(2)\"></img>\n' );
document.write( '<img src=\"https://mmccall0813.github.io/skinImg/3.png\" onclick=\"setSkin(3)\"></img>\n' );
document.write( '<img src=\"https://mmccall0813.github.io/skinImg/4.png\" onclick=\"setSkin(4)\"></img>\n' );
document.write( '<img src=\"https://mmccall0813.github.io/skinImg/5.png\" onclick=\"setSkin(5)\"></img>\n' );
document.write( '<img src=\"https://mmccall0813.github.io/skinImg/6.png\" onclick=\"setSkin(6)\"></img>\n' );
document.write( '<img src=\"https://mmccall0813.github.io/skinImg/7.png\" onclick=\"setSkin(7)\"></img>\n' );
document.write( '<img src=\"https://mmccall0813.github.io/skinImg/8.png\" onclick=\"setSkin(8)\"></img>\n' );
document.write( '<img src=\"https://mmccall0813.github.io/skinImg/9.png\" onclick=\"setSkin(9)\"></img>\n' );
document.write( '<img src=\"https://mmccall0813.github.io/skinImg/10.png\" onclick=\"setSkin(10)\"></img>\n' );
document.write( '<img src=\"https://mmccall0813.github.io/skinImg/11.png\" onclick=\"setSkin(11)\"></img>\n' );
document.write( '<img src=\"https://mmccall0813.github.io/skinImg/12.png\" onclick=\"setSkin(12)\"></img>\n' );
document.write( '<img src=\"https://mmccall0813.github.io/skinImg/13.png\" onclick=\"setSkin(13)\"></img>\n' );
document.write( '<img src=\"https://mmccall0813.github.io/skinImg/14.png\" onclick=\"setSkin(14)\"></img>\n' );
document.write( '<img src=\"https://mmccall0813.github.io/skinImg/15.png\" onclick=\"setSkin(15)\"></img>\n' );
document.write( '<img src=\"https://mmccall0813.github.io/skinImg/16.png\" onclick=\"setSkin(16)\"></img>\n' );
document.write( '<img src=\"https://mmccall0813.github.io/skinImg/17.png\" onclick=\"setSkin(17)\"></img>\n' );
document.write( '<img src=\"https://mmccall0813.github.io/skinImg/18.png\" onclick=\"setSkin(18)\"></img>\n' );
document.write( '<img src=\"https://mmccall0813.github.io/skinImg/19.png\" onclick=\"setSkin(19)\"></img>\n' );
document.write( '<img src=\"https://mmccall0813.github.io/skinImg/20.png\" onclick=\"setSkin(20)\"></img>\n' );
document.write( '<img src=\"https://mmccall0813.github.io/skinImg/21.png\" onclick=\"setSkin(21)\"></img>' );
